### ISSUE TITLE
No easy way to get validator address

### ISSUE THREAD

**Issue by melekes** [tendermint/mintnet-kubernetes#10]
except `kubectl exec -c tendermint tm-1 -- cat /tendermint/priv_validator.json`, which is bad because we are transferring this info over the network.

It is needed by basecoin like apps for sending txs (at least for the guide):

```
kubectl exec -c app tm-0 -- basecoin tx send --to 0x53ED985A64A6C87F48637644CC6F86606A56C39E --amount 5 --coin "CITI/USD" --from /tendermi
nt/priv_validator.json
```

**Comment by melekes** [comment]
What is the right way to do it? Add `tendermint show_validator_address`?

**Comment by ebuchman** [comment]
is this not sufficient `curl -s http://localhost:46657/status | jq .result[1].pub_key` ?

**Comment by ebuchman** [comment]
oh sorry thats a pubkey

**Comment by ebuchman** [comment]
maybe we should make the address part of the `pub_key.json` file?

**Comment by melekes** [comment]
could be the option

**Comment by ethanfrey** [comment]
Yes, I think the easiest to simply expose the address everywhere we expose the public key.  They are often required together, and while it is trivial to generate the address in go code, it is very hard in a client.

**Comment by ethanfrey** [comment]
Meaning both the pub_key.json file as well as the status call.

**Comment by melekes** [comment]
And what is the standard way to acquire someone's address?

Suppose me and my 2 friends installed a mintnet on 3 machines. Each of us is a validator. Now I want to send some money to my friend Bob. So he needs to ssh to his machine and `cat /priv_validator.json` to see his address???, copy it and send it to me via slack (or write it on a piece of paper) ?

**Comment by ebuchman** [comment]
no no no. let's add it to the /status .. how bout that?

**Comment by ethanfrey** [comment]
This whole priv_validator should not be used by client keys, just for validator nodes.  I think Bucky used it just to get something working and signing asap. And it is okay for now.

If you want a user account, you should create it on your desktop.

I'm working on code for the clients (users of the system, not node operators) to easily manage keys... maybe tomorrow evening you can use it?

**Comment by melekes** [comment]
Ah, now I get it. Thanks, Frey!

I suppose this is the example of the client key: https://github.com/tendermint/basecoin-examples/blob/master/trader/data/key.json

Just realized mintnet-k8s will need a small redesign:

```
Before:
(N pods: TM plus APP) <-> one service

After:
(N pods: TM) <-> tm-tier
(M pods: APP) <-> app-tier
```

> no no no. let's add it to the /status .. how bout that?

i won't be needing this as it turnes out

**Comment by ethanfrey** [comment]
Yes, that is a "client" key.  Whoever uses the cli is totally outside of the k8 world. (except in demos)

Isn't it best to leave the TM and APP together in one pod? Seems much safer to only connect over localhost.

**Comment by melekes** [comment]
ok, that was a crazy idea :) will go to sleep

**Comment by melekes** [comment]
Closing this. Thanks to @ethanfrey was able to identify a flaw here https://github.com/tendermint/mintnet-kubernetes/blob/master/examples/basecoin/app.yaml#L44

We must not use validator's pub key, but rather generate another one in a format of https://github.com/tendermint/basecoin-examples/blob/master/trader/data/key.json

**Comment by ebuchman** [comment]
doh! sorry, that was obvious - thanks frey. no need for validator
addresses. see the new `basecoin key` command on develop!
